### ISSUE TITLE
Simulcast video tracks with lower resolution will always be pending

### ISSUE THREAD

**Issue by bekriebel** [livekit/livekit-server#112]
**Describe the bug**
When using simulcast with low resolutions, video tracks will always be in a pending state. This causes events like mute status changes to never be recognized by the server or broadcast to clients.

**Server**
- Version: [0.12.5]
- Environment: Docker image on fly.io

**Client**
- SDK: js
- Version: 0.12.1

**To Reproduce**
1. Start a conference with lower video resolution (`VideoPresets43.vga` and simulcast enabled. 
2. Have debug logging enabled
3. Mute/unmute the video track
4. Note that the `mute status changed` log is ever printed

**Expected behavior**
Tracks should not be considered pending if the total number of expected tracks are being sent, regardless of that number.

**Additional context**
This appears to be getting caused by a combination of how the JS Client SDK handles simulcast tracks with lower resolution and expectations of the livekit-server.

In `participant.go - SetTrackMuted`, if a track is considered pending the function returns early and does not change the Muted status server side or send `onTrackUpdated` events. https://github.com/livekit/livekit-server/blob/1bcaf9d0ea2681aadb6f60bfe42062f252903a42/pkg/rtc/participant.go#L586-L588

In `participant.go - onMediaTrack`, pending tracks are only removed from the pending status if the track isn't simulcasted, or if the number of established tracks is 3. https://github.com/livekit/livekit-server/blob/1bcaf9d0ea2681aadb6f60bfe42062f252903a42/pkg/rtc/participant.go#L824-L827

In the JS Client SDK, if the starting resolution is not high enough, only one simulcast track (for a total of two tracks) will be sent. https://github.com/livekit/client-sdk-js/blob/64dc4b52fc363fe34e8ac58427f233868b0d0e7e/src/room/participant/LocalParticipant.ts#L389-L417

Either the client code would need to be modified to always sent two tracks, or the sever code needs to remove the assumption that simulcasted tracks will always have three active encoding levels.

**Comment by bekriebel** [comment]
I may be wrong about exactly what is happening here. I just tested using `VideoPresets43.qhd`, which gives me 3 published encodings, and I'm still getting the issue. I have to go to at least `VideoPresets43.hd` (or disable simulcast) for it to consistently work.

**Comment by bekriebel** [comment]
It is certainly still related. The odd thing is that when using qhd, the client says it is passing 3 encoding tracks (f, h, q) but the server is still only getting two (f, h). When using vga, the client and server both think only two are being passed and for hd and above, client and server agree on 3 tracks. I haven't tracked down what is causing this other discrepancy when using qhd.

For now, I'll just be disabling simulcast for my project. Since I'm using lower resolutions, I gain no benefit from needing to use qhd or above. I do get some savings from the two simulcast tracks with a low resolution, so it'd be great to be able to do so when this is resolved.

**Comment by davidzhao** [comment]
hey @bekriebel, this is a good catch. this is due to an assumption of how simulcasted tracks are managed. I'll have a PR out for this.
