### ISSUE TITLE
how to use DataChannel transfer bin file at server side and client side,or client side and client side?

### ISSUE THREAD

**Issue by seamanm** [livekit/livekit-server#117]
how to use DataChannel transfer bin file at server side and client side,or client side and client side?thanks

**Comment by davidzhao** [comment]
See https://docs.livekit.io/guides/room/data#data-message-from-participants for starters.

to publish data from the server side, you can use Go server SDK to send chunks of the file with [publishData](https://pkg.go.dev/github.com/livekit/server-sdk-go#LocalParticipant.PublishData)
