### ISSUE TITLE
Cannot connect to insecure Websocket

### ISSUE THREAD

**Issue by rjahrj** [livekit/livekit-server#123]
I am trying to set up a server to test this and use your frontend example before i build my own, but every time i try to connect I get the error saying can not connect to insecure websocket from https. I then set up a reverse proxy and secured the backend, but it still gives me the same issue! Any advice?

**Comment by davidzhao** [comment]
@rjahrj unfortunately, there isn't a way to get around the SSL requirement imposed by browsers. If you have a reverse proxy terminating SSL in front of the signal connection, ensure that it's a certificate issued by a Certificate Authority, and not self-signed. See [deployment guide](https://docs.livekit.io/guides/deploy/) for more info on this topic.

**Comment by yelban** [comment]
Do I have to enable reverse proxy separately to enable TLS WSS?

Is there any way to set the wss TLS certificate path?

**Comment by davidzhao** [comment]
today, you'd have to use a separate reverse proxy such as nginx. we'll share some examples of this in the near future.

**Comment by yelban** [comment]
Thanks @davidzhao , this is exactly what I needed.

**Comment by yelban** [comment]
Thanks @davidzhao . If there is already a running vm on vultr and nginx with SSL certs running, how do I get nginx to proxy livekit's wss tls?

**Comment by rajil** [comment]
where can i find [livekit.nginx.conf](https://raw.githubusercontent.com/livekit/livekit-server/master/deploy/livekit.nginx.conf)?
