### ISSUE TITLE
Help Setting Up Production Server

### ISSUE THREAD

**Issue by rjahrj** [livekit/livekit-server#124]
Hey everyone, I am requesting some guidance in setting up a production server. I am still pretty new when it comes to messing around with docker and kubernetes. I currently have a digital ocean kubernetes cluster running with a nginx ingess controller installed. I have read the documentation and need a little help regarding using a helm chart to finish setting it up the right way. if anyone can help me, i would very much appreciate it!

**Comment by davidzhao** [comment]
Sorry, our helm chart doesn't support Digital Ocean at the moment.
