### ISSUE TITLE
Missing the ability to lock down a node, and force new calls to be initialized on a different one

### ISSUE THREAD

**Issue by cmaster11** [livekit/livekit-server#127]
I'm currently experimenting with running LiveKit in a Kubernetes environment, and I'm load testing it heavily.

I'm using a Redis instance to balance the rooms, and it all works well until we hit CPU limits.

The scenario is:

* We have CPU requests/limits set, which means our pods cannot use e.g. more than 3.5CPUs.
* We have HPA enabled, so new pods come up depending on the current avg CPU usage of the pods.

New clients connect via LB, and if one of LK pods is currently running at e.g. >95% CPU, then it would be advisable for new rooms to be created on ANOTHER node, instead of the busy one. But, at the moment, I don't see a way to do that without altering the source code in some way.

So, I feel like there is no way to tell a specific node "do not accept new rooms" at runtime. This can cause a lot of chaos in autoscaling environments because already-busy nodes will keep receiving new rooms 🤔 

Is this a currently missing feature? 

Thanks!

**Comment by davidzhao** [comment]
Have you checked out the `sysload` [node selector](https://github.com/livekit/livekit-server/blob/master/config-sample.yaml#L125)? It allows you to set a max per-CPU load to stop assigning new rooms onto the node.

Feel free to re-open if it doesn't work for you.

**Comment by cmaster11** [comment]
Ah! That can be a good solution, thank you very much :) Definitely missed that config entry!
