### ISSUE TITLE
Support for multiple video codes in the same room

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit-server#128]
When a participant has an active track published with VP8, and another subscriber that has successfully received that codec. If a new H264 track gets published to the room, the existing subscriber will fail to receive the track.

This is due to Pion MediaEngine making simple assumptions that if a video codec is already negotiated in the session, it will ignore other codecs that could support the new tracks that have been added.

This limitation is in Pion, and [here's a PR](https://github.com/pion/webrtc/pull/1918) aimed at fixing it.

**Comment by davidzhao** [comment]
The current workaround in LiveKit is to only support a single codec with `enabled_codecs`. However, it'd be great to remove this limitation. While all clients support VP8, some may want to leverage the hardware H.264 en/decoders on mobile devices by enabling mixed H.264/VP8 rooms.

**Comment by cnderrauber** [comment]
fixed by pr #191
