### ISSUE TITLE
Data messages not sending in subscribe only mood

### ISSUE THREAD

**Issue by jibon57** [livekit/livekit-server#144]
In my case I wanted user can only participants without sharing microphone or webcam. It's like subscribe only/listen only mood. But in that mood data messages aren't sending. I'm getting this error in my JS client:

`Uncaught (in promise) DOMException: An attempt was made to use an object that is not, or is no longer, usable` 

Am I misunderstanding somewhere? But if that user connect with webcam then messages are sending as expected.

**Comment by davidzhao** [comment]
I'm not able to reproduce this.. can you reproduce with our [sample app](https://github.com/livekit/client-sdk-js#sdk-sample)?

**Comment by jibon57** [comment]
@davidzhao thanks for reply. This is how I'm trying:

```
const textEncoder = new TextEncoder();

let room: Room;
try {
    room = await connect(url, token, {
        logLevel: LogLevel.debug,
        audio: false,
        video: false
    });
    currentRoom = room;
} catch (error) {
    console.error(error);
    return;
}

room
    .on(RoomEvent.ParticipantConnected, handleParticipantConnected)
    .on(RoomEvent.ParticipantDisconnected, handleParticipantDisconnected)
    .on(RoomEvent.DataReceived, handleDataReceived)

const msg = textEncoder.encode("Test");
currentRoom.localParticipant.publishData(msg, DataPacket_Kind.RELIABLE);
```

**Comment by lukasIO** [comment]
I found a reproducible setup for the example app.
Just add one line of data publishing to the example.ts at ~ line 256
```ts
   ...
    .on(RoomEvent.MediaDevicesError, (e: Error) => {
      const failure = MediaDeviceFailure.getFailure(e);
      appendLog('media device failure', failure);
    });

  room.localParticipant.publishData(encoder.encode('my test message'), DataPacket_Kind.RELIABLE);

  appendLog('room participants', room.participants.keys());
  room.participants.forEach((participant) => {
    participantConnected(participant);
  });

```

**Comment by davidzhao** [comment]
There must be some other state change that happens depending on the browser. 

I think we should switch the publishData awaiter to check [readyState](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/readyState) instead. Let me know if either of you have time to create a PR. It's ok if not, I can get to it later this week.

**Comment by jibon57** [comment]
@davidzhao yes, I think if we check status & wait around 1 seconds then should be fine. Something here:
https://github.com/livekit/client-sdk-js/blob/2995a22f9b948699c629df910c163eb846ccb72c/src/room/RTCEngine.ts#L394

   ```
 if (kind === DataPacket_Kind.LOSSY && this.lossyDC) {
      if (this.lossyDC.readyState === 'connecting') {
        await sleep(1000);
      }
      this.lossyDC.send(msg);
    } else if (kind === DataPacket_Kind.RELIABLE && this.reliableDC) {
      if (this.reliableDC.readyState === 'connecting') {
        await sleep(1000);
      }
      this.reliableDC.send(msg);
    }
```
