### ISSUE TITLE
TURN reports failed to handle Refresh-request

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit-server#156]
**Describe the bug**
When running in production, the logs would print lines like:

```
turn ERROR: 2021/10/20 18:55:24 error when handling datagram: failed to handle Allocate-request from 212.225.225.45:21336: relay already allocated for 5-TUPLE
turn ERROR: 2021/10/20 19:21:13 error when handling datagram: failed to handle Refresh-request from 212.225.225.45:12676: no allocation found 212.225.225.45:12676:0.0.0.0:443
```

**Server**
- Version: 0.13.5

**Client**
- SDK: Web

**To Reproduce**
It's not clear how to reproduce this. Related tickets mention FireFox 91 on Android. https://github.com/pion/turn/issues/206

**Comment by jibon57** [comment]
@davidzhao I'm facing this problem when I'm trying to send data message. From console `WebRTC: ICE failed, add a STUN server and see about:webrtc for more details`. From ICE Stat column I can see all failed. Any work around? This is mostly happening with Firefox.

**Comment by heromiyo** [comment]
Having the same issue:
TEST results:
Connecting to signal connection via WebSocket

Connected to server, version 0.15.3.

Establishing WebRTC connection

Can connect via TURN

Can publish audio

published 62 audio packets

Can publish video

ERROR: Could not get RTCStats

Resuming connection after interruption

------ LOGS

livekit_1  | 2022-02-09T05:52:00.675Z   ERROR   livekit.turn    v2@v2.0.6/server.go:184 error when handling datagram: failed to handle Allocate-request from 41.77.144.98:51596: relay already allocated for 5-TUPLE

**Comment by davidzhao** [comment]
@heromiyo what browser/OS/device are you using the connection tester with?

**Comment by heromiyo** [comment]
Chrome Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by cnderrauber** [comment]
I have created a pr for turn@v2.0.8 to fix Allocation already exist 

For Refresh-request allocation not found, the only case I can reproduce is packet out of order in client close. 
The sequence is :
1. client allocation relay , connect to sfu
2. allocation will expire, client send refresh to refresh allocation's lifetime
3. at same time, client closed(user leave), send refresh with 0 lifetime to delete the allocation

at server side, packet 2, 3 reorder during network transfer, so turn server receive packet 3 first, delete allocation, then packet 2 received, allocation not found.  It only happened in client closing, so will not cause problem. 
I think this issue can be closed now @davidzhao 

Another information about turn but not this problem, for refresh allocation, the client behavior is different, and some clients will interrupt when refresh-request is lost.
1. chrome will refresh allocation 1 minute before it expired, and retry until success or allocation expired(will cause rtc connection failed). That is RFC's recommend.
2. safari will refresh allocation 1 minute before it expired, and retry 30 second then disconnect if failed.
3. firefox will refresh 10 second before expired, retry until expired. If network have a high lost rate in these 10 seconds, it is easy to fail.
