### ISSUE TITLE
Video track sometimes fails to publish on high latency SFU (incoming SSRC failed Simulcast probing)

### ISSUE THREAD

**Issue by bekriebel** [livekit/livekit-server#166]
**Describe the bug**
When connecting clients to a high-latency SFU node through a low-latency Signaling node, the video track for a participant will sometimes fail to be published properly. This results in a participant that appears to have published its video track, but is not available for subscribing by other peers.

This causes a repeating server-side error of `pc ERROR: 2021/11/02 18:56:14 Incoming unhandled RTP ssrc(726609843), OnTrack will not be fired. incoming SSRC failed Simulcast probing`

**Server**
- Version: 0.13.6
- Environment: multi-region cluster on fly.io
- One node located in Frankfurt, Germany, the other in Seattle, WA, US. Connecting with clients in Seattle, WA.

**Client**
- SDK: js
- Version: 0.13.6

**To Reproduce**
1. Create a room in the high-latency node
2. Connect to the room with with multiple clients using the low-latency node as the signaling server.
3. If the error does not occur, continue to reconnect the clients. If reconnecting six clients at once, I can normally reproduce the error within 2-4 reconnect attempts. I can also reproduce the error with just two clients connected (one reconnecting), but it takes longer to reproduce.
4. One of the client's video tracks will fail to be seen by other clients. When this happens, the server logs begin repeating the error: `pc ERROR: 2021/11/02 18:56:14 Incoming unhandled RTP ssrc(726609843), OnTrack will not be fired. incoming SSRC failed Simulcast probing`. This error continues until the offending client disconnects or the video track is unpublished.

**Expected behavior**
Tracks should always publish reliably.

**Screenshots**
Client who's track is not seen by others:
![image](https://user-images.githubusercontent.com/183779/139930636-b17fd421-3ae1-4b11-82f8-c4c96846357f.png)

Participant info as seen by another client:
![image](https://user-images.githubusercontent.com/183779/139930806-e902e45e-d557-433d-873a-958a389bf641.png)

Server logs:
![image](https://user-images.githubusercontent.com/183779/139931050-8b3c9ef7-88ce-4245-bbf7-23b3c0df6e00.png)

**Additional context**
The error will sometimes be seen as a single error when clients are connecting. However, the track still publishes properly unless the error continues to repeat on the server.

When clients are disconnecting, this error is sometimes seen:
`pc ERROR: 2021/11/02 19:23:29 Incoming unhandled RTP ssrc(2760947722), OnTrack will not be fired. EOF`

The error appears to be getting generated here: https://github.com/pion/webrtc/blob/5dc7245beea6a757f33c73110335eeaf76868a82/peerconnection.go#L1473
and logged here:
https://github.com/pion/webrtc/blob/5dc7245beea6a757f33c73110335eeaf76868a82/peerconnection.go#L1510

**Comment by jibon57** [comment]
I faced similar problem if user has slow internet connection. If 2 users having slow connection & tried to shared webcam almost same time then that error message will show up. During that time video don't publish until reconnect or re-share.

**Comment by jesusvaldivia** [comment]
Hi @bekriebel 
I have the same problem, in my case it happens when the SFU server is very far from the redis server.
Did you find any solution?

**Comment by bekriebel** [comment]
> Hi @bekriebel I have the same problem, in my case it happens when the SFU server is very far from the redis server. Did you find any solution?

I have not. It is a very rare occurrence for me, so I have not taken more time to debug this issue yet. If anyone from LiveKit needs help reproducing or debugging this, please let me know.

**Comment by davidzhao** [comment]
@alex-bluetrain does the published track actually fail for you? Sometimes this line can be printed without there being an actual problem (packets arriving earlier than signal negotiation).

If you are seeing publish failures, could you describe how we might be able to reproduce it? We haven't been able to reproduce this issue on our end.

**Comment by alex-bluetrain** [comment]
@davidzhao the published track randomly fails, those messages can be seen when it's actually working fine, I'll try to get a repro for this, it's a bit difficult to pinpoint it.

**Comment by davidzhao** [comment]
@bekriebel @alex-bluetrain I believe we've finally tracked this down! It was a bug in pion https://github.com/pion/webrtc/issues/2054. It's fixed in #346 and will be released in the next build.
