### ISSUE TITLE
Regarding Multi-region support?

### ISSUE THREAD

**Issue by CensorKao** [livekit/livekit-server#170]
Do you have more information about Multi-region support? Does all the participant's media stream need back to the original node or just delivery in each region and selective redirect to original server?

**Comment by bekriebel** [comment]
There are two activities involved: signaling and SFU.

Signaling can be distributed. That is, different participants can connect to different signaling nodes (backed by redis) and will receiving information about the room that they are connected to.

SFU, which handles the actual media streams, currently is not distributed. A node is selected using one of the node selector methods (https://github.com/livekit/livekit-server/blob/6a80beedfca6e7f96c1bef8b28406714f7942f82/config-sample.yaml#L127-L139). For example, if you use `regionaware` it will choose the closest available node based on the distance from the signaling server that the first participant has connected to. Once a room is established, any other participant that joins the room will be directed to that node for the SFU by whatever signaling server they are connected to.


As an example, you have two nodes: one in Seattle, WA, US, one in Frankfurt, Germany and you are using `regionaware` node selection.
The first participant joins the conference from somewhere in North America, they connect to the SEA node which sees that this is new conference and creates the room on the SEA node.
A second participant joins from somewhere in Europe, they connect to the FRA node which sees the existing room in SEA. The FRA node tells the participant to connect to the SEA node for the SFU.

This all assumes that you have some way of making sure that the users end up connecting to their closest node for signaling. There are many ways of doing that (geographic DNS, BGP, etc.) - but that part is not handled by LiveKit.


I've seen some mentions of also distributing the SFU functions at some point, but that isn't something that is available today. Right now, individual rooms live specifically on a single node.

Hope this helps!

**Comment by CensorKao** [comment]
> There are two activities involved: signaling and SFU.
> 
> Signaling can be distributed. That is, different participants can connect to different signaling nodes (backed by redis) and will receiving information about the room that they are connected to.
> 
> SFU, which handles the actual media streams, currently is not distributed. A node is selected using one of the node selector methods:
> 
> https://github.com/livekit/livekit-server/blob/6a80beedfca6e7f96c1bef8b28406714f7942f82/config-sample.yaml#L127-L139
> 
> 
> For example, if you use `regionaware` it will choose the closest available node based on the distance from the signaling server that the first participant has connected to. Once a room is established, any other participant that joins the room will be directed to that node for the SFU by whatever signaling server they are connected to.
> As an example, you have two nodes: one in Seattle, WA, US, one in Frankfurt, Germany and you are using `regionaware` node selection. The first participant joins the conference from somewhere in North America, they connect to the SEA node which sees that this is new conference and creates the room on the SEA node. A second participant joins from somewhere in Europe, they connect to the FRA node which sees the existing room in SEA. The FRA node tells the participant to connect to the SEA node for the SFU.
> 
> This all assumes that you have some way of making sure that the users end up connecting to their closest node for signaling. There are many ways of doing that (geographic DNS, BGP, etc.) - but that part is not handled by LiveKit.
> 
> I've seen some mentions of also distributing the SFU functions at some point, but that isn't something that is available today. Right now, individual rooms live specifically on a single node.
> 
> Hope this helps!

Thanks. That would be great, if closest media nodes can forward media streams to the first joined node.
