### ISSUE TITLE
ARM compatibility

### ISSUE THREAD

**Issue by brunocalado** [livekit/livekit-server#175]
**Describe the bug**
This command don't work in a ARM enviroment.
`docker run --rm livekit/livekit-server generate-keys`

**Server**
- Version: last
- Environment: arm64 + ubuntu

**To Reproduce**
run `docker run --rm livekit/livekit-server generate-keys` in a ubuntu arm64

**Expected behavior**
generate the keys

**Screenshots**
![image](https://user-images.githubusercontent.com/4999783/140978731-41feab57-3151-4bc6-b2af-2bbe8cb06fba.png)

**Comment by davidzhao** [comment]
Ah, looks like our arm64 builds were not done properly. Could you try this?

`docker run --rm livekit/livekit-server:v0.14.1-SNAPSHOT generate-keys`
