### ISSUE TITLE
broken link docs

### ISSUE THREAD

**Issue by brunocalado** [livekit/livekit-server#176]
this link is broken: https://docs.livekit.io/deploy/kubernetes/ports-firewall#firewall

**Comment by davidzhao** [comment]
where might this be linked from?

**Comment by brunocalado** [comment]
https://docs.livekit.io/deploy/kubernetes/

**Comment by davidzhao** [comment]
I meant.. where did you find the link, so that we could fix it.

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/141177762-857f3167-2903-40e3-a002-eb5c06e4db76.png)
