### ISSUE TITLE
[REQUEST] Oracle Cloud Guide

### ISSUE THREAD

**Issue by brunocalado** [livekit/livekit-server#181]
Hi.

Would be possible to add a guide to install livekit in a ubuntu 20 at oracle cloud?
https://docs.livekit.io/deploy/vm

The oracle machine is free: https://www.oracle.com/th/cloud/free/#always-free with 10TB transfer

**Comment by davidzhao** [comment]
It's possible to do this now with our new VM setup process: https://docs.livekit.io/deploy/vm/

It supports cloud-init, so that should be straight forward.
https://blogs.oracle.com/linux/post/easy-provisioning-of-cloud-instances-on-oracle-cloud-infrastructure-with-the-oci-cli
