### ISSUE TITLE
Add Content-type header to webhook POST requests

### ISSUE THREAD

**Issue by lukasIO** [livekit/livekit-server#184]
The http spec says the header **should** be present, eventhough it is not explicitly required.

> Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".

from what I can see, something like this should do it ?
```diff
for _, url := range n.urls {
		r, err := http.NewRequest("POST", url, bytes.NewReader(encoded))
		if err != nil {
			// ignore and continue
			n.logger.Error(err, "could not create request", "url", url)
			continue
		}
		r.Header.Set(authHeader, token)
+		r.Header.Set("content-type", "application/json")
		_, err = http.DefaultClient.Do(r)
		if err != nil {
			n.logger.Error(err, "could not post to webhook", "url", url)
		}
	}

```

**Comment by davidzhao** [comment]
this is great! nice work
