### ISSUE TITLE
Livekit Server Crushed while idle.

### ISSUE THREAD

**Issue by kemal3ds** [livekit/livekit-server#192]
Server crashes while at idle and gettin error while on room connection.

**Server**
- Version: [0.14.0]
- Environment: [DO - Ubuntu 20.04 (
LTS) x64 2 vCPUs 2GB / 60GB Disk]
- For TLS connection, proxy pass over domain plesk and send cloudflare. Cloudflare redirects to port 7880/7881 without tls

**Client**
- SDK: ["livekit-server-sdk": "0.5.6"]
- SDK: livekit-client": "0.14.1"

For error:
1. two clients are connected to room
2. a client disconnected
3. received error
`  ERROR   livekit logger/logger.go:34     missing stats worker    {"participantID": "PA_jrCScwEBKLc9"}
github.com/livekit/protocol/logger.Errorw
        /root/go/pkg/mod/github.com/livekit/protocol@v0.10.1-0.20211109000312-b3847c8d35ff/logger/logger.go:34
github.com/livekit/livekit-server/pkg/telemetry.(TelemetryService).TrackUnpublished
        /root/livekit-server/pkg/telemetry/events.go:89
github.com/livekit/livekit-server/pkg/rtc.(MediaTrack).AddReceiver.func4
        /root/livekit-server/pkg/rtc/mediatrack.go:370
github.com/livekit/livekit-server/pkg/sfu.(WebRTCReceiver).closeTracks
        /root/livekit-server/pkg/sfu/receiver.go:665
github.com/livekit/livekit-server/pkg/sfu.(WebRTCReceiver).forwardRTP.func1.1
        /root/livekit-server/pkg/sfu/receiver.go:546
sync.(Once).doSlow
        /usr/local/go/src/sync/once.go:68
sync.(Once).Do
        /usr/local/go/src/sync/once.go:59
github.com/livekit/livekit-server/pkg/sfu.(WebRTCReceiver).forwardRTP.func1
        /root/livekit-server/pkg/sfu/receiver.go:544
github.com/livekit/livekit-server/pkg/sfu.(WebRTCReceiver).forwardRTP
        /root/livekit-server/pkg/sfu/receiver.go:562
[2:54 PM]
udp_mux ERROR: 2021/11/15 11:54:33 could not read udp packet: read udp4 0.0.0.0:7882: use of closed network connection`

**Comment by davidzhao** [comment]
Does the error actually cause participants to disconnect?

Can you see if it reproduces on 0.14.2?

**Comment by kemal3ds** [comment]
No, when a client leave the room, we get this error also server crushed when idle, like there is no connection for 1 or 2 hour and after we can't connect to server anymore needed to restart.

**Comment by davidzhao** [comment]
`also server crushed when idle, like there is no connection for 1 or 2 hour and after we can't connect to server anymore needed to restart.` it sounds that's the actual problem.. we haven't seen this behavior before nor have gotten other reports. I wonder if it's related to your computer/network.

**Comment by davidzhao** [comment]
closing given the issue is stale/unreproducible
