### ISSUE TITLE
[Feature request] add API for individual room info + metadata add during room create

### ISSUE THREAD

**Issue by jibon57** [livekit/livekit-server#196]
1) add API for individual room info
At present we can list all the rooms using `ListRooms​` API call but will be better if we can get information only for individual room directly instated of looping over rooms. Something like `getRoom` by passing `name of the room`. 

2) metadata add during room create
At present it isn't possible to add metadata during create room. Only after create room using `UpdateRoomMetadata` API call. Will be better if we can add metadata during create. Something like:

```
const opts = {
  name: 'my room-unique-id',
  emptyTimeout: 10 * 60,
  maxParticipants: 20,
  metadata: {
    title: 'Room Title',
    params: {
      'test': 01
    }
  }
}
svc.createRoom(opts).then((room: Room) => {
  console.log('room created', room)
})
```

**Comment by lukasIO** [comment]
It'd be great if someting `getRoom`(s) would accept an array of strings as roomNames. This would also enable to get subsets of rooms.

**Comment by davidzhao** [comment]
metadata on create will be added as well :)

**Comment by jibon57** [comment]
@davidzhao do you think it will be better to have meeting's title as a field too? Similar way you added for participate? I think changing meeting name to meeting identify/ID will be more meaningful

**Comment by davidzhao** [comment]
@jibon57 that's outside of scope of LiveKit. A user could easily attach it to the room metadata and/or their own UI.
