### ISSUE TITLE
Access Token is confusing and over complicated !

### ISSUE THREAD

**Issue by thusinh1969** [livekit/livekit-server#204]
Hi,

We have been struggling with Access Token and its complexity. Our design is simple as everything is going through our back-end server, and the back-end server (which controls everything) will connect to the LiveKit server on users' behalf. The client only connects socket/peer/SFU as it requires. Almost all actions like creating a room, deleting a room, listing users, kicking users, managing subscribers/publishers tracks, and such are managed through the back-end (except simulcast) and the back-end server will talk to LiveKit.

The Access Token was just not designed for ease of use in such a case where the back-end server has to create a new Access Token for itself (the Administrator) all the time for each room to be administered which is way too complicated as we have so many rooms and such.

Is there any way to make LiveKit easier for such (popular) scenarios?

We also found that even if we reserve some action for end-user to request directly to LiveKit, it is also very complicated and a new set of token have to be generated all the time, unnecessarily.

Maybe we have not read / understood LiveKit access token thoroughly ? Please help.

Thanks,
Steve

**Comment by thusinh1969** [comment]
After walking through real-life coding example, we found it pretty good actually. We implement in Python, it works.

Thanks,
Steve

**Comment by aehlke** [comment]
@thusinh1969 have a reference implementation? I'm also about to use python
