### ISSUE TITLE
How do we control "recording" from calling Server API instead of using SDK ?

### ISSUE THREAD

**Issue by thusinh1969** [livekit/livekit-server#206]
We use Python as our core back-end and do not actually want to over-engineer with NPM/GO. Most of the things will work during Client/Server co-operation, but recording.

The question is how do we control "**_recoding_**" from calling LiveKit Server HTTP-API instead of using SDK?

Thanks,
Steve

**Comment by frostbyte73** [comment]
You'll need to use `protoc` to generate a python binding for https://github.com/livekit/protocol/blob/main/livekit_recording.proto, and then implement something similar to https://github.com/livekit/server-sdk-js/blob/main/src/RecordingServiceClient.ts or https://github.com/livekit/server-sdk-go/blob/main/recordingclient.go but in python

**Comment by thusinh1969** [comment]
> You'll need to use `protoc` to generate a python binding for https://github.com/livekit/protocol/blob/main/livekit_recording.proto, and then implement something similar to https://github.com/livekit/server-sdk-js/blob/main/src/RecordingServiceClient.ts or https://github.com/livekit/server-sdk-go/blob/main/recordingclient.go but in python

How wonderful :) Thank you.

**Comment by davidzhao** [comment]
Twirp services are also just HTTP.. so you could just post JSON payloads to it.
