### ISSUE TITLE
Quickly muting and unmuting an audio track adds a 1-2 second delay to the audio

### ISSUE THREAD

**Issue by bekriebel** [livekit/livekit-server#219]
**Describe the bug**
When an audio track is disabled and re-enabled quickly, it will often cause a delay to be introduced into the audio track. The delay is a noticeable 1-2 seconds and it causes the audio track to be off-sync with the video track if both are published. If multiple clients are connected, the delay often arises in all of the connected clients, but not always the same amount of delay. If either the published or subscriber disconnects and reconnects, the delay will be fixed.

**Server**
- Version: [0.14.2]
- Environment: Docker image on Fly.io

**Client**
- SDK: js
- Version: 0.14.3

**To Reproduce**
1. Connect two clients to a room using the client-js sample app. This is easiest seen in two windows on one machine, but reproduces across multiple machines as well. It is best to use a low-latency server so normal audio has minimal delay.
2. Mute the audio of one client so you are only testing from a single source, referred to from here on out as the sender.
3. Notice that on the receiver has minimal delay and the audio is in sync with the video stream (I tested by snapping my fingers for a good indicator).
4. Use the Disable Audio button to mute track on the sender, wait a few seconds and re-enable the audio. Note that no delay is introduced.
5. Disable the audio track and then quickly enable it again (double tap the button)
6. Check the audio delay on the receiver, often times a 1-2 second delay will be introduced

It may take multiple tries of step 5 to get the issue to reproduce. If I tap the button 10 times in quick succession, (5 mute/unmute cycles), it reproduces for me almost every time. It's possible that the issue also reproduces when not muting and unmuting quickly, but I was not able to observe this.

**Expected behavior**
Audio delay should not be introduced by disabling/enabling the audio track. Audio and video should remain in sync.

**Screenshots**
N/A

**Additional context**
It's possible this is a client-js bug and not livekit-server, but I do not have a good setup to test this at the moment. I did not notice anything relevant in the client or server-side logs.

**Comment by davidzhao** [comment]
hey @bekriebel, does the delay eventually go away? (i.e. catch up) or would the sync issue be present for the rest of the session?

**Comment by bekriebel** [comment]
I'll set up a test later. I think it remains, but will confirm.

**Comment by bekriebel** [comment]
> hey @bekriebel, does the delay eventually go away? (i.e. catch up) or would the sync issue be present for the rest of the session?

I was mistaken. Yes, if I keep my audio enabled, it does catch back up, typically within about a minute. However, if I continue to mute and unmute the track it doesn't seem to sync back up while in the muted state. Since my app uses enable/disable with a Push-to-talk feature, it means those users are staying out of sync most of the time.

**Comment by davidzhao** [comment]
@bekriebel I think this might be an issue with interactions between browser and SFU. we've noticed jitter buffer delay increasing after mute/unmute. will investigate

![image (1)](https://user-images.githubusercontent.com/320582/144900536-54e5bb84-b1e5-4626-a94b-df22e8a785b5.png)

**Comment by bekriebel** [comment]
@davidzhao good to know. If this is possibly something that can't be fixed in the code (a native browser WebRTC issue), what about the option for muting without actually disabling the track? Ideally it would stop audio being sent to the SFU, but it could also just stop the SFU from forwarding the audio to subscribers. That would be ideal for push-to-talk application since I imagine it'd be faster than fully disabling/enabling the track each time.

This would also have the added benefit of being able to continue tracking audio volume levels and would allow for the option of a signal when the user is trying to talk when muted. For example, the Jitsi web client pops this up if it detects audio levels while mute is enabled: 
![image](https://user-images.githubusercontent.com/183779/144924003-54a6e227-0726-46cf-88ea-939904bee283.png)

**Comment by cnderrauber** [comment]
I can't reproduce this problem on my machine, are you both observe this problem?

@davidzhao 
jitter buffer delay is always increase since it's a stat of sum metric. need observe the graph of jitterBufferDelay/jitterBufferEmittedCount_in_ms

> It is the sum of the time, in seconds, each audio sample or a video frame takes from the time the first packet is received by the jitter buffer (ingest timestamp) to the time it exits the jitter buffer (emit timestamp). ....... This metric increases upon samples or frames exiting, having completed their time in the buffer (and incrementing jitterBufferEmittedCount). The average jitter buffer delay can be calculated by dividing the jitterBufferDelay with the jitterBufferEmittedCount.

**Comment by davidzhao** [comment]
@cnderrauber you are totally right. my mistake

**Comment by bekriebel** [comment]
Has any work been done on this? I'm still running 14.2 due to the redis issue, so haven't tried it against the newer versions.

**Comment by boks1971** [comment]
@bekriebel Nothing specific. We have not been able to reproduce this issue like @cnderrauber mentioned above.

I just tried again with the latest too and cannot reproduce it. I tried with Chrome 98 (the latest). Are you on Chrome or a different browser?

**Comment by putrafajarh** [comment]
i tested on ```https://example.livekit.io/``` and ```https://livekit.io/playground``` connect 2 participant, mute and unmute video. its delay, more often i mute and unmute its more delay

**Comment by bekriebel** [comment]
I finally got a chance to test newer server versions. I'm not able to reproduce this with v0.15.5, so it appears to have been fixed somewhere between 0.14.2 and 0.15.5.
