### ISSUE TITLE
LiveKit Recording manual is very confusing and not usable !

### ISSUE THREAD

**Issue by thusinh1969** [livekit/livekit-server#236]
Hi,

Thanks for good open-source LiveKit. We are experimenting it now. However, with recording, we found that the manual/guide is  very confusing and does not instruct end-to-end process for each scenario. Would be great if the author redoes the manual and split them into an individual scenarios in FULL (from config to deploy/run/stop):
1) Standard alone from step 1 -- step end and how to scale them
   - Config
   - Run
   - Stop
   - Resume
2) Service mode in separate VM and how to scale them
   2.1. Service mode with default templates
        - Deploy pre-requisite services for scaling for file or streaming (can be 2 scenarios ?)
        - Call via ws_url API
        - Call via Go/Node SDK
        - Start - Stop - Resume
   2.2. Service mode with custom templates
        - Deploy pre-requisite services for scaling for file or streaming (can be 2 scenarios ?)
        - Call via ws_url API
        - Call via Go/Node SDK
        - Start - Stop - Resume
       
If you read the manual now, it is jumping/linking over the places and extremely confusing. Also once we tried to start a service / standard alone docker, there are a bunch of GStreamer errors, and not sure why errors are there and if this error can be ignored !?

Can not run recording now at all, unfortunately, if we can run it successfully, will be happy to do a merge for manual.

The example also produce 24M movide MP4 but not playable !
mkdir -p ~/livekit-recordings
docker pull livekit/livekit-recorder
docker run --rm --name demo \
    -e LIVEKIT_RECORDER_CONFIG='log_level: debug' \
    -e RECORDING_REQUEST='{"url":"https://www.youtube.com/v/dQw4w9WgXcQ","filepath":"/output/url-demo.mp4"}' \
    -v ~/livekit-recordings:/output \
    livekit/livekit-recorder & \
sleep 60 && docker stop demo

Thanks,   
Steve

**Comment by davidzhao** [comment]
hi Steve, we appreciate your feedback, but please refrain from filing duplicate issues in multiple repos. this increases our work load and makes it harder for us to follow up.
