### ISSUE TITLE
Voice on Foundry VTT Reload - Old Problem

### ISSUE THREAD

**Issue by brunocalado** [livekit/livekit-server#244]
**Situation**
Press F5 to solve some Foundry VTT issue is very common. But, when you do that you loose comunication. This happened of jitsi and we had to stop use audio on Foundry leaving only the video. Is it possible to make voice still work even if you reloaded Foundry VTT (F5)

**Comment by davidzhao** [comment]
hey @brunocalado, I think you meant to file this issue with Foundry VTT?
