### ISSUE TITLE
GetParticipant gives Internal Server Error 500  and ListParticipants empty !

### ISSUE THREAD

**Issue by thusinh1969** [livekit/livekit-server#253]
* **Internal Server 500 when  GetParticipant**:
Call API: https://localhost/twirp/livekit.RoomService/GetParticipant
GetParticipant_body = {
        'room': "98754958675986",
        'identity': "45435hmfguhoig"
    }
headers = {
        "Authorization": "Bearer " + admin_room_token
    }

admin_room_token is valid as being used in other room creation OK.  Both room and identity are correct.

LiveKit server return Internal Server Error 500. No idea why and how ?

* **Meanwhile, ListParticipants give empty although there are 2 persons in room video-chat OK**.
Call API: https://localhost/twirp/livekit.RoomService/ListParticipants
ListParticipants_body = {
        'room': "98754958675986",
    }
headers = {
        "Authorization": "Bearer " + admin_room_token
    }

LiveKit server return empty.

Any hint please.
Steve

**Comment by davidzhao** [comment]
Listing a participant requires roomAdmin and the name of the room. It's different from the permission needed to create a room.

See [Access token perms](https://docs.livekit.io/guides/access-tokens#room-permissions)

**Comment by thusinh1969** [comment]
> Listing a participant requires roomAdmin and the name of the room. It's different from the permission needed to create a room.
> 
> See [Access token perms](https://docs.livekit.io/guides/access-tokens#room-permissions)

Yes I used roomAdmin token for accessing all API except CreateRoom.

**Comment by thusinh1969** [comment]
Yes I used roomAdmin token for accessing all room'related API (room name inside of course) except CreateRoom.

**Comment by thusinh1969** [comment]
Yes I used roomAdmin token for accessing all room-related API (room name inside of course) except CreateRoom. Same result.

**Comment by thusinh1969** [comment]
Yes I used roomAdmin token for accessing all room-related API (room name inside of course) except CreateRoom. Same result.

**Comment by thusinh1969** [comment]
My bad, found a bug in my code :( ... Sorry. It works.
