### ISSUE TITLE
Unable to connect to insecure websocket from https

### ISSUE THREAD

**Issue by falconray0704** [livekit/livekit-server#263]
**Describe the bug**
Access my livekit-server which deploy with docker, and test it with "https://example.livekit.io/#/".

Got popup alert "Unable to connect to insecure websocket from https"

**Server**
- Version: [0.4.12]
- Environment: [docker on VPS with public IP]
- Following github README to launch server :
- `docker run --rm \
  -p 7880:7880 \
  -p 7881:7881 \
  -p 7882:7882/udp \
  -e LIVEKIT_KEYS="APIDnog5ufxoPxs: fGuOev1wW6lL8CrsjzlQ1YODKgE1DsrY7LpTKLGeGoxA" \
  livekit/livekit-server \
  --dev`

**Client**
- SDK: [chrome browser]
- Version: [0.x.x]

**To Reproduce**
1. launch server by official docker image
2. Access server from chrome browser with "ws://clifford.work:7880"
3. Click "connect" on the web page;
4. See error alert popup "Unable to connect to insecure websocket from https"

Have any suggestion for me to fix it?
I just want to try the server on my VPS fist.

**Comment by jibon57** [comment]
You should try `wss://clifford.work:7880`. Also make sure you've configured SSL for that port otherwise use proxy server. Like here: https://github.com/livekit/livekit-server/blob/master/deploy/livekit.nginx.conf

**Comment by davidzhao** [comment]
it appears you don't have SSL termination set up.

To test it without SSL, your best bet is to run the [JS test app](https://github.com/livekit/client-sdk-js#sdk-sample) on localhost (which doesn't have the same browser restrictions for)
