### ISSUE TITLE
`ListRooms` with room names specified returns not only the requested room(s)

### ISSUE THREAD

**Issue by lukasIO** [livekit/livekit-server#313]
**Describe the bug**
The `ListRoom` service returns more rooms than specified (tested with latest server-sdk-js).

**Server**
- Version: [0.15.1]
- Environment: [custom]
- any other information about your deployment setup

**Client**
- SDK: [server-sdk-js]
- Version: [0.5.8]

**To Reproduce**
1. call `sc.listRooms` with an array of one room name. e.g. `['123-43' ]`
2. inspect response
3. return values include (in my case) two rooms: 
```targetRooms 123-43 [
  {
    sid: 'RM_vSS9XXx2csCW',
    name: '122-40',
    ...
  },
  {
    sid: 'RM_D9EZwUTwvuAx',
    name: '123-43',
   ....
  }
```
**Expected behavior**
Only the info for the requested room(s) should be returned

**Screenshots**

**Additional context**

**Comment by boks1971** [comment]
Probably a result of this change - https://github.com/livekit/livekit-server/pull/312.

**Comment by lukasIO** [comment]
ah, sorry, I put the wrong server version, it's actually 0.15.1

**Comment by davidzhao** [comment]
listRooms filter is introduced after 0.15.2 and is still unreleased on the server side. we'll cut a new release shortly, stay tuned.
