### ISSUE TITLE
does the cloud init livekit version needs update?

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [livekit/livekit-server#355]
Hello,
do we need to update the version here to `0.15.2`? 

https://raw.githubusercontent.com/livekit/livekit-server/master/deploy/cloud-init.ubuntu.yaml
https://github.com/livekit/livekit-server/blob/master/deploy/cloud-init.amzn2.yaml

**Comment by davidzhao** [comment]
Hey @ahmed-adly-khalil, we really should.. I'm in the process of updating docs, but we'll be moving to the new deployment generator as [outlined here](https://github.com/livekit/livekit-server#single-node-server).

We'll make a note in here shortly.
