### ISSUE TITLE
Room stuck with `packetio.Buffer full, discarding write`

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit-server#401]
**Describe the bug**
A user reported a freeze during a session. The following logs are printed.

```
Feb 03 14:24:36 livekit[663]: 2022-02-03T14:24:36.375+0100        ERROR        livekit.mux        mux/mux.go:122        mux: ending readLoop dispatch error packetio.Buffer is full, discarding write
Feb 03 14:24:36 livekit[663]:         {"room": "73741964-bd91-4652-803e-e1b8b7a293ef", "roomID": "RM_tNbUBZLRCCE2", "participant": "XYZ", "pID": "PA_vQ83QWbB3HVP"}
Feb 03 14:24:36 livekit[663]: github.com/pion/webrtc/v3/internal/mux.(*Mux).readLoop
Feb 03 14:24:36 livekit[663]:         /XYZ/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.16/internal/mux/mux.go:122
```

At which point, subscriber could no longer receive video from `XYZ`; while `XYZ` could continue to subscribe to the other person's stream.

This seems related to what we had seen on FireFox when it rejects packets due to SRTPReplayProtection. Perhaps that'd be a good way to reproduce the underlying buffer issue.

**Server**
- Version: 0.15.3

**Client**
- SDK: JS / Chrome

**Comment by jibon57** [comment]
I can reproduced this problem too. I posted it before here: https://livekit-users.slack.com/archives/C01KVTJH6BX/p1643719965134149

**Comment by cnderrauber** [comment]
fixed by #413

**Comment by davidzhao** [comment]
@CensorKao While this is happening, are you able to connect as a new participant?

Which browser/client are you using?

**Comment by CensorKao** [comment]
> @CensorKao While this is happening, are you able to connect as a new participant?
> 
> Which browser/client are you using?

It seems resloved in [v0.15.5]. No errors happened again.

**Comment by davidzhao** [comment]
thanks for confirming that!
