### ISSUE TITLE
VM: init_script.sh

### ISSUE THREAD

**Issue by Mist-Hunter** [livekit/livekit-server#407]
Hello, 

I'm looking forward to deploying what looks to be great software, but I'm struggling to find good exmaples of [Docker networking](https://github.com/livekit/livekit-server/issues/404).

I decided to try and do a VM based deployment instead of Docker as described [here](https://docs.livekit.io/deploy/vm/#deploy-to-a-vm).
A startup script is mentioned:

> Copy the file init_script.sh to the VM

But when[ I look through this git repo](https://github.com/livekit/livekit-server/search?q=init_script.sh), I'm not seeing it. Is the documentation correct? It looks as though perhaps the script is just setting up docker anyways, but I still wouldn't mind seeing what it does so I can better understand what needs to be done. 

Any help appreciated!

**Comment by davidzhao** [comment]
Hey @Mist-Hunter, the init script is generated for your specific domain. Run this script (also in README) to get started: `docker run --rm -it -v$PWD:/output livekit/generate`.

When it asks you for cloud-init or init script, choose the latter
