### ISSUE TITLE
one of key-file or keys must be provided in order to support a secure installation

### ISSUE THREAD

**Issue by localhosted** [livekit/livekit-server#454]
I built the server and after uploading it to my VPS I try to run it but I get this error:

> ubuntu$  ./livekit-server

> 2022-02-22T01:23:12.339Z        INFO    livekit logger/logger.go:26     using single-node routing
one of key-file or keys must be provided in order to support a secure installation

**Comment by davidzhao** [comment]
You'd need to configure keys in a [configuration file](https://docs.livekit.io/deploy/#configuration). Please refer to [setup instructions](https://docs.livekit.io/guides/getting-started#setting-up-the-server) on generating a config
