### ISSUE TITLE
Server does not support Redis TLS Connection

### ISSUE THREAD

**Issue by alexbeattie42** [livekit/livekit-server#470]
**Describe the bug**
The server is unable to connect to a redis instance that requires TLS. Digital Ocean managed redis requires TLS and livekit gives the following error when trying to start: `unable to connect to redis: EOF`. DO has a post [about this](https://docs.digitalocean.com/support/when-connecting-to-redis-i-get-an-endoffile-error./)

**Server**
- Version: [v0.15.4]
- Environment: [DO Kubernetes, DO managed Redis]

**To Reproduce**
1. Deploy a livekit-server instance to DO Kubernetes
2. Create a DO managed redis instance
3. Get the pod logs for the livekit-server pod and observe the EOF error.

**Expected behavior**
The server should connect to redis over TLS if it is specified in the configuration.

**Additional context**
I have tested the connection to redis with `redis-cli` and the database is fine. When I omit the `--tls` flag from the `redis-cli` command ping fails in the same way as in livekit. [Something like this](https://github.com/go-redis/redis/issues/756) can be implemented.

**Comment by davidzhao** [comment]
Thanks for the detailed note. Sounds like the work-around is to accept TLS without validation?

That sounds fine to me. Feel free to make a PR!
