### ISSUE TITLE
Multiple rtc room can be generated for a single room

### ISSUE THREAD

**Issue by b20132367** [livekit/livekit-server#483]
By the time when the following snippet is entered by multiple threads of execution,
https://github.com/livekit/livekit-server/blob/4bc03d84353171a89f6bffaa36739f0a05540a95/pkg/service/roommanager.go#L322-L327

each creates a separate rtc room and return it.

**Comment by davidzhao** [comment]
@b20132367 you are right! There's a small window where there could be a race. we'll need to lock and then check again before creation.

let me know if you are interested in submitting a PR for this.

**Comment by b20132367** [comment]
I'm more than happy to contribute!
