### ISSUE TITLE
Error: error compiling magefiles

### ISSUE THREAD

**Issue by ngocdtph03070** [livekit/livekit-server#494]
When I run the command: mage and  receive error

# command-line-arguments
.\magefile.go:277:13: undefined: syscall.Rlimit
.\magefile.go:278:9: undefined: syscall.Getrlimit
.\magefile.go:278:27: undefined: syscall.RLIMIT_NOFILE
.\magefile.go:284:9: undefined: syscall.Setrlimit
.\magefile.go:284:27: undefined: syscall.RLIMIT_NOFILE
Error: error compiling magefiles

**Comment by davidzhao** [comment]
I see, syscall isn't available on windows. Can you give [this branch](https://github.com/livekit/livekit-server/tree/fix-magefile-windows) a try?

**Comment by ngocdtph03070** [comment]
@davidzhao Thank you, I will retry this branch

**Comment by davidzhao** [comment]
let me know how it works. I'll merge it in once you confirm!
