### ISSUE TITLE
Limit speaker events to Microphone tracks

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit-server#509]
Currently we will trigger a speaker detected event if audio activity is found on any audio track.

This doesn't make a ton of sense when audio level changes within a screenshare audio track.

**Comment by sibis** [comment]
@davidzhao, I would like to pick this up. I will debug the code to understand the areas that need to be worked on. will get back if I need any help.

**Comment by davidzhao** [comment]
that's amazing to hear @sibis ! let me know if you have any questions. [This](https://github.com/livekit/livekit-server/blob/master/pkg/rtc/participant.go#L635) is likely the right place for the filter.

**Comment by sibis** [comment]
Thanks @davidzhao. Have made the change accordingly and raised this [PR](https://github.com/livekit/livekit-server/pull/553). Please take a look at it.
