### ISSUE TITLE
Webhook `participant_joined` may be called too early

### ISSUE THREAD

**Issue by dwirya** [livekit/livekit-server#514]
**Describe the bug**
Receiving the webhook `participant_joined` and checking State in ParticipantInfo, the state is `JOINING`, not `JOINED`. We have a system that changes the subscription of that participant's tracks, so if we receive the webhook and try to update the subscription, we'll get the error that participant does not exist

**Server**
- Version: 0.15.5
- Environment: AWS EC2
- Not on Kubernetes, running Docker container straight on EC2

**Client**
- SDK: server-sdk-go
- Version: 0.9.1

**To Reproduce**
1. set up server to receive webhook from LiveKit server
2. join a room
3. receive webhook on the server and print the state of ParticipantInfo.

**Expected behavior**
In my case it was showing `JOINING`, not `JOINED`. For the webhook `participant_joined`, I expect the webhook to reflect the actual state of the participant.

**Screenshots**

**Additional context**

**Comment by davidzhao** [comment]
Fixed in #535
