### ISSUE TITLE
 How to deploy behind a nat? 

### ISSUE THREAD

**Issue by skiffer-git** [livekit/livekit-server#521]
**Describe the bug**

**Server**
- Version: [0.x.x]
- Environment: [e.g. local dev, EKS]
- any other information about your deployment setup

**Client**
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
1. two clients are connected to room
2. 3rd client joins
3. 3rd client does '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by davidzhao** [comment]
For how-tos, please refer to our [deployment docs](https://docs.livekit.io/deploy/)
