### ISSUE TITLE
Docker does not generate any files

### ISSUE THREAD

**Issue by ericnething** [livekit/livekit-server#539]
I have tried running the docker container `livekit/generate` in every way I can figure on multiple linux machines, which technically use podman. The files that are supposed to be generated in the mounted volume never appear, so I cannot get a cloud-init or startup script to deploy.

I am running podman 3.4.4.

I tried running both of these commands, but neither produces any files.
```
docker run --rm -v$PWD:/output livekit/generate --local
docker run --rm -it -v$PWD:/output livekit/generate
```

Has anyone else encountered this problem? Does anyone know how to fix it?

**Comment by davidzhao** [comment]
@ericnething, can you paste the full output of running `docker run --rm -v$PWD:/output livekit/generate --local` ?

The command will write the output to `$PWD`, your current directory. It's possible that env var isn't set on your machine. feel free to replace it with another directory that exists.

**Comment by ericnething** [comment]
I have tried many different ways of running this command. The following is the recommended way to do it for podman on linux, because it is rootless. It seems to either genrate no files, or the volumes are never mounted.

```
~/D/livekit-data> sudo podman run --rm -it -u root -v $PWD:/output:Z livekit/generate --local
Generated livekit.yaml that's suitable for local testing

Start LiveKit with:
docker run --rm \
    -p 7880:7880 \
    -p 7881:7881 \
    -p 7882:7882/udp \
    -v $PWD/livekit.yaml:/livekit.yaml \
    livekit/livekit-server \
    --config /livekit.yaml \
    --node-ip=10.88.0.7

Server URL:  ws://localhost:7880
API Key: API6T4TQ7eUFeRD
API Secret: 0OYdURueo9hIBquc9kX00fm8L9jbueUxR2YmN8OtLFxA

Here's a test token generated with your keys: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODM4MzI4NjAsImlzcyI6IkFQSTZUNFRRN2VVRmVSRCIsImp0aSI6InRvbnlfc3RhcmsiLCJuYW1lIjoiVG9ueSBTdGFyayIsIm5iZiI6MTY0NzgzMjg2MCwic3ViIjoidG9ueV9zdGFyayIsInZpZGVvIjp7InJvb20iOiJzdGFyay10b3dlciIsInJvb21Kb2luIjp0cnVlfX0.ztXqGYYRb3Bu7EbUc9uie9veMRaMtq-MHGd91AQbhAs

An access token identifies the participant as well as the room it's connecting to
```

**Comment by davidzhao** [comment]
awesome, thanks for sharing this!
