### ISSUE TITLE
neither side can receive the message(MessageCase.UPDATE)

### ISSUE THREAD

**Issue by hadesss123** [livekit/livekit-server#572]
**Describe the bug**
We found that in some failed calls, both parties have successfully joined the signaling room, and both parties have successfully connected to the media server. But neither side can receive the message(MessageCase.UPDATE) that the other party has joined the signaling room. I want to know, under what conditions will the server send the message(MessageCase.UPDATE) that the other party has successfully joined the signaling room.

**Server**
- Version: [livekit-server v0.15.5]

**Client**
- SDK: [android]
- Version: [0.9.0-SNAPSHOT]
@davidzhao

**Comment by davidzhao** [comment]
I'm not quite sure what you mean. Participant updates are always sent as long as they are connected to the same room. How do you reproduce this?

**Comment by hadesss123** [comment]
I can't reproduce this problem, it is a problem that occurs in some rooms of the production environment. Is there a log to indicate that the server sent the partifipant updates @davidzhao
