### ISSUE TITLE
[Question] vp8 on iPhone Safari

### ISSUE THREAD

**Issue by caiiiycuk** [livekit/livekit-server#573]
Hi! 

I am sorry that I created bug for question. It's because I can't ask in Slack due the sanctions for Russian citizens :(

Thank you for the great product. I tested it and it works perfectly. But I can't understand how it supports forwarding vp8 streams to iPhone devices. Is livekit transcode vp8 to h264 under the hood? For example I start sharing screen on Desktop Chrome, so it will be encoded with vp8 codec which is not supported on iPhone Safari. But with livekit I was able to see this stream. Does it mean that livekit not just forwards but also converts the video stream? I don't have any other idea how it can work.

I looked in sources code, but does not find anything related to vp8 -> h264 conversion.
 
I saw a benchmark on livekit docs page. According to it livekit on 16 core server process 5 publisher and 1k subscribers with 90% of load. Is it because of video stream conversion? if it just forwarding, why are the numbers so small? I believe that just for forwarding only the network is the matter. Am I wrong?
 
Thank you.

**Comment by davidzhao** [comment]
iPhone devices support decoding VP8 via software. [RFC7742](https://datatracker.ietf.org/doc/html/rfc7742#section-5) indicates all WebRTC clients must support both codecs.

We do not convert video on the server side, but instead [utilize simulcast](https://blog.livekit.io/an-introduction-to-webrtc-simulcast-6c5f1f6402eb)

**Comment by caiiiycuk** [comment]
Wow thank you. So the information from caniuse is wrong?
![изображение](https://user-images.githubusercontent.com/1727152/160518023-ea9a0dd3-64f8-4bf1-b197-60c366d23f11.png)
Partial support in Safari refers to being limited to macOS 11.3 or later.

When I tried to forward vp8 to iPhone with plain ion-sfu it never worked for me. 
However this is great news. Thank you.
