### ISSUE TITLE
Duplicate candidate address in SDP

### ISSUE THREAD

**Issue by CensorKao** [livekit/livekit-server#578]
**Describe the bug**

@davidzhao @davidliu 

Two candidate have the same ip address/connection protocol and port number. Is this normal?

Android Client Received SDP:

a=candidate: 462404801 1 udp 2130706431 55.31.219.199 14103 typ host
a=candidate: 462404801 2 udp 2130706431 55.31.219.199 14103 typ host
a=candidate: 2793196833 1 tcp 2124414975 55.31.219.199 7881 typ host tcptype passive
a=candidate: 2793196833 2 tcp 2124414975 55.31.219.199 7881 typ host tcptype passive

I have set interfaces in livekit.yaml. My livekit.yaml,
  interfaces:
     includes:
       - en0
     excludes:
       - docker0

**Server**
- Version: [v0.15.6]
- Environment: [local dev]

**Client**
- SDK: [Adnroid]
- Version: [v0.9.0]

**Comment by CensorKao** [comment]
> Yes.. this is normal. it indicates that it's for RTP and RTCP: https://tools.ietf.org/id/draft-ietf-mmusic-ice-sip-sdp-14.html#rfc.section.5.1

RTP and RTCP share the same server IP and Port/Protocol? Please check above received SDP, Aren't the next two repeated?
a=candidate: 462404801 1 udp 2130706431 55.31.219.199 14103 typ host
a=candidate: 462404801 2 udp 2130706431 55.31.219.199 14103 typ host

**Comment by boks1971** [comment]
One is for RTP (the first line has `1` after `462404801`) and one for RTCP (the second line has `2`)
