### ISSUE TITLE
Current speakers not sent to new participants

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit-server#607]
When a new participant joins, if there are current active speakers, it will not get those updates.

Since speaker updates are sent as deltas, we should be updating new participants with the list of current active speakers.

**Comment by boks1971** [comment]
Addressed in this PR - https://github.com/livekit/livekit-server/pull/676 by sending an update when subscribing to a new participant. Note that the update is sent only if the subscribed to participant is an active speaker at that time. If not, subsequent changes to active speaker state will be sent to the client.
