### ISSUE TITLE
Mobile devices on 4g or the devices using mobiles hotspot - do not connect

### ISSUE THREAD

**Issue by ksarpotdar** [livekit/livekit-server#610]
**Describe the bug**
Tried the playground (https://livekit.io/playground) url. It doesn't connect the mobile on 4g data or devices on mobile hotspot, with another device on the wifi. Devices on wifi connect to each other well.

**Server**
- Version: [0.x.x] demo version of playground server
- Environment: [e.g. local dev, EKS]
- any other information about your deployment setup

**Client** demo version of playground server
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
1. go to https://livekit.io/playground and type any meeting 1234 and user id abc on mobile (but on mobile 3g/4g data)
2. connect laptop to https://livekit.io/playground with meeting 1234 and user id bcd but with the wifi connection. and create two of such connections, They connect to each other well.
3. now give mobile hotspot to the devices and try to connect to meeting,
5. Checking the chrome://webrtc-internal shows that the iceconnection, connectionstate, signaling state everything is stuck up at "new". It doesn't progress.

**Expected behavior**
All devices connect to each other and stream video regardless they are on which connection (mobile 3g/4g/wifi /corporate LAN etc)

**Screenshots**
The steps given. no screen shot.

**Additional context**
I think mobiles are behind the symmetric NAT and it needs turn servers  in normal mesh peer-to-peer connection and my app works with such TURN. But how to use TURN servers in this SFU? or how the SFU uses internally the IP provided by iceCandidates to make a connection to the TURN server? or can this SFU also act like a TURN server if the device is behind the symmetric NAT?

**Comment by davidzhao** [comment]
LiveKit comes with an embedded [TURN server](https://docs.livekit.io/deploy#improving-connectivity-with-turn). I'm unable to reproduce this specific connection issue through a hotspot.

Which carrier are you testing with?

**Comment by ksarpotdar** [comment]
Dear David

Thanks for the response. 

I am testing it in India on vodafone carrier. I did testing once again. This time I tried with unmute audio and it got transmitted very easily.. It worked, so probably its not an issue with the livelink server or TURN related. 

So probably some issue in the preview code after run (it won't open camera on mobile). But I am not able to debug on mobile, as to what exactly it the problem.

**Comment by anupriya17** [comment]
We tested on android and ios with 4g India (Airtel, jio, Idea), we've not seen any connectivity issues so far.

**Comment by ksarpotdar** [comment]
Thanks, As I mentioned, it must be the issue in the front end code I guess, its not taking camera on my device . After second attempt I realized that audio is going well and only video isn't going. Thus it can't be server issue. Its not opening the camera on my device, I guess.

We can close this issue. There isn't any action needed on software front.
