### ISSUE TITLE
bytes/packets node stats not updating correctly

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit-server#617]
Node stats related to bytes/packets (bps, pps, total in/out) seem to update at a much slower pace than when we persist node metrics. As a result, bps/pps often display as 0 (if it hasn't changed between the last update).

Repro steps:

1. run server locally, and join with two clients
2. run `./bin/livekit-server --config config.yaml list-nodes` every few seconds

Expected result:

bytes/packets would change each time, bps/pps display actual values

Actual result:

bytes/packets updates every 5 or 6 runs, bps/pps display as 0 for majority of the runs.

**Comment by bekriebel** [comment]
@davidzhao This still seems to be happening with a build on the latest HEAD (59112b9). It's less frequent, but I'm still often seeing 0s on BPS with 7 clients connected all sending and receiving audio and video.

![image](https://user-images.githubusercontent.com/183779/164353375-943c5617-b693-4150-9ce6-7eb77dcf0a24.png)
