### ISSUE TITLE
Multi-Region Signaling Routing?

### ISSUE THREAD

**Issue by ty-lightstream** [livekit/livekit-server#630]
The docs aren't super clear on how routing of signaling works for multi-region with redis. Say I have a room that is homed on ServerA in RegionA. Now a client near to ServerB in RegionB tries to join the room. Does ServerB setup a websocket proxy to ServerA? Or does ServerB redirect the client to ServerA (and it tries to reconnect there)? Or does ServerB terminate the signaling for the client (reading and proxying messages with ServerA via redis), with media of course routing through ServerA?

I guess I'm trying to understand in a multi-region redis setup if ServerA and ServerB ever need to communicate directly for signaling bridging (and thus would have to somehow know public addressing), or if redis pub/sub is used to facilitate such communication? My assumption is the latter, but I wanted to confirm.

thx!
Ty

**Comment by bekriebel** [comment]
> Or does ServerB terminate the signaling for the client (reading and proxying messages with ServerA via redis), with media of course routing through ServerA?

This is my understanding. I know for certain that the signaling continues to go through the node that the client first connected to and the media goes through the node hosting the room. I don't believe the nodes talk directly to each other; that is all done via redis.

**Comment by davidzhao** [comment]
In a multi-node setup, the websocket connection can be terminated by any server. The messages then get routed to the media instance hosting the room via Redis. There is no proxying happening within LiveKit.

**Comment by zii** [comment]
@davidzhao Multi-region nodes, do they share the same Redis? Need to connect to Redis remotely?

**Comment by davidzhao** [comment]
Yes, that is correct. They need to connect to the same Redis instance in order to route peer to peer.

We'll be introducing other messaging options other than Redis. That's coming soon,.

**Comment by gofastlily** [comment]
Is there any update on non-Redis messaging methods?
