### ISSUE TITLE
Production Ready

### ISSUE THREAD

**Issue by mohit67890** [livekit/livekit-server#64]
Hello, I tried this and it looks great to me. 
i read your online documentation. Its well documented. However, it says that it should be used in the same manner for production purposes.
Can you help me more into explaining what would be the ideal way that this can be used in production. 

Since, it has docker. I am thinking of using AWS ECS for this. Would be great, If you can provide some context in that regard.

Thank You

**Comment by davidzhao** [comment]
Hey @mohit67890, please reference our deployment documentation: https://docs.livekit.io/guides/deploy/

You can get this to work with ECS. While we no longer publish official terraform scripts for ECS, you can find them here:

https://github.com/livekit/livekit-server/tree/44488f078cdecf776f45a97f381a1aefb8c7ddc4/deploy/aws-ecs

hopefully they could serve as a guide for you.

**Comment by mohit67890** [comment]
Thank You for that.
I have checked that you have gke support as well..
I will try to go with that.. 

I just wanted to know how will I get the apikey and secret when I deploy it on the GKE.

Sorry, I'm little new to kubernetes, so have little knowledge about that..

Thank You

**Comment by davidzhao** [comment]
API/Secret are provided by you.. please refer to the getting started guide: https://docs.livekit.io/guides/getting-started/

**Comment by mohit67890** [comment]
Okay, I might be a little confused here. 
So, basically If I generate the API and key from the bin and provide the same in the gke yaml file. 
So, it will work right?

I thought it will be different for every livekit-server.

Thank You

**Comment by davidzhao** [comment]
yup, it should :) the different instances will be using the same set of api key/secret pairs. When deployed, your clients may connect to any of the instances.
