### ISSUE TITLE
If we configure redis, when one party hangs up,the participant will not receive the notification (ParticipantDisconnectedEvent) until 30 seconds later

### ISSUE THREAD

**Issue by skiffer-git** [livekit/livekit-server#659]
**Describe the bug**
If we do not configure redis, when one party hangs up, the participant can receive the notification (ParticipantDisconnectedEvent) soon.
If we configure redis, when one party hangs up,the participant will not receive the notification (ParticipantDisconnectedEvent) until 30 seconds later

**Server**
- Version: [0.15.5]
- Environment: [ubuntu]
- any other information about your deployment setup

**Client**
- SDK: [flutter]
- Version: [LiveKit Flutter SDK: livekit_client: 0.5.9]

**Comment by davidzhao** [comment]
closing as no additional information is received.
