### ISSUE TITLE
Any C++ sdk

### ISSUE THREAD

**Issue by randydom** [livekit/livekit-server#672]
Hello , Any C++ sdk please ?

**Comment by davidzhao** [comment]
We don't have one right now. but this is something we are planning to offer in the future.

**Comment by randydom** [comment]
Any updates here ?!

**Comment by davidzhao** [comment]
we have something planned. hoping to have a beta out by November this year.

**Comment by evehal** [comment]
Any good news for cpp?

**Comment by davidzhao** [comment]
We are working on it. It's taking a bit longer than expected. Current ETA is Q1 of next year.

**Comment by randydom** [comment]
Still waiting for the C++ sdk

**Comment by davidzhao** [comment]
cpp SDK will be built on top of our Rust common core. See [client-sdk-rust](https://github.com/livekit/client-sdk-rust)

**Comment by randydom** [comment]
Any release date ?

**Comment by davidzhao** [comment]
I'm terrible at predicting when something will be done.. so I'll stop trying :)

**Comment by gongxinheng** [comment]
It's [here](https://github.com/livekit/client-sdk-cpp) now. WIP
