### ISSUE TITLE
Background noise / static on receivers when muted & using DTX

### ISSUE THREAD

**Issue by bekriebel** [livekit/livekit-server#675]
**Describe the bug**
When DTX is enabled and a mic has background noise but no significant audio when it is muted, receivers will continue to hear the background noise. DTX seems to continue playing this baseline level when the mic is muted. If you are making louder sounds when muting, audio will go silent as expected. If DTX is disabled, audio will always go silent as expected. It helps to use a lower quality mic that pics up more white noise static when quiet.

**Server**
- Version: [0.15.7]
- Environment: Regional clusters running from docker
- any other information about your deployment setup

**Client**
- SDK: [js]
- Version: [0.17.5]

**To Reproduce**
1. two clients are connected to room, you can use https://example.livekit.io/
2. Turn volume up on user B
3. Have some static like background noise on user A's mic - nothing too loud.
4. Mute A's mic while not talking
5. Hear that the background noise continues to be heard on user B

Repeat the same steps but add normal talking audio when muting the audio. You'll observe that the audio goes completely silent.

**Expected behavior**
Audio should always go silent when muting the mic.

**Screenshots**
N/A

**Additional context**

This seems to be the exact same problem as this issue described for Jitsi: https://github.com/jitsi/jitsi-media-transform/issues/383. It was apparently fixed by forwarding a small number of 0 audio level packets after muting so DTX stops adding noise, see: https://github.com/jitsi/jitsi-media-transform/pull/384

I'll see if I can replicate a similar fix on LiveKit, but someone else may be able to add this kind of fix faster.

**Comment by davidzhao** [comment]
thanks for this report! really great analysis into the issue.

I think sending a few 0 audio packets should fix this. I think this will be similar to our fix for video where blank frames are forwarded.

**Comment by bekriebel** [comment]
> I think sending a few 0 audio packets should fix this. I think this will be similar to our fix for video where blank frames are forwarded.

Yeah, that's what I was hoping. I have a test commit that I was playing with that uses `WritePaddingRTP` in downtrack's `func (d *DownTrack) Mute(muted bool) {` after removing the check in that function that stops it from working on audio tracks... however, that doesn't seem to be working for some reason regardless of the number of padding packets that I send. Perhaps I'm just not understanding the code and the padding packets aren't doing what I expect.

**Comment by davidzhao** [comment]
padding packets wouldn't work here. since they would get ignored by the receiving client. It'll have to be an actual opus frame, where it's has encoded silence. 

Janus does it [here](https://github.com/meetecho/janus-gateway/blob/master/src/postprocessing/pp-opus-silence.h)
