### ISSUE TITLE
I want to optimize the intranet delay to 25-50ms, is it possible?

### ISSUE THREAD

**Issue by Bmixo** [livekit/livekit-server#74]
![11](https://user-images.githubusercontent.com/25509024/127743880-b3c33c65-cc5d-457c-87a6-ee80e31cdf69.PNG)

I ran a test on k8s on the intranet. The program was deployed behind the k8s balance and connected to the client machine using wss. In the case of only two clients, the test showed that the video delay was very high, the average value was around 180ms, but I The ping between intranet machines is within 1ms. I want to optimize the intranet delay to 25-50ms. Is it possible? Can it be achieved? If possible, tell me the approximate method available.
thanks.

**Comment by Bmixo** [comment]
25.473 
25.254
=0.219s

26.328
26.155
=0.173s

37.313
37.164
=0.149s

28.048
27.875
=0.173s

28.864
28.654
=0.21s

avg = (0.219s+0.173s+0.149s+0.173s+0.21s) / 5 = 0.1848s = 184 ms

**Comment by davidzhao** [comment]
hey @Bmixo, the end to end latency depends on a few factors:

1. publisher capture
2. publisher encoding
3. transmission from publisher to SFU
4. LiveKit internal processing
5. transmission from SFU to subscriber
6. subscriber decode
7. subscriber render

The only place where we have direct control over is 4, and it sounds that 3 and 5 should be fairly minimal for you. The biggest variability will come from the browser that you are testing with, and how they are encoding/decoding the packets. I did an experiment locally and averaged a little over 100ms. 

We've also [measured end to end latency](https://docs.livekit.io/guides/deploy/benchmark/#audio-only) of the LiveKit system with our load tester, which doesn't include client encoding/decoding steps. It was <50ms even when transmitting between different data centers.

<img width="886" alt="Screen Shot 2021-07-31 at 9 41 35 PM" src="https://user-images.githubusercontent.com/320582/127759651-e81bcc14-2eb4-4486-9e1c-c646a1e62377.png">

<img width="929" alt="Screen Shot 2021-07-31 at 9 46 41 PM" src="https://user-images.githubusercontent.com/320582/127759650-e7b1fb60-3079-4803-b0a4-20117a3020a1.png">

**Comment by Bmixo** [comment]
Thank you for your answer, I will use the graphics hardware to encode the video stream
