### ISSUE TITLE
Plan for merge pion/sfu

### ISSUE THREAD

**Issue by truanguyenvan** [livekit/livekit-server#89]
Hi, I see pion/sfu has updated relay sfu 8 days ago, do you have a merge plan yet?

**Comment by davidzhao** [comment]
We don't need the relay feature as of yet so there are no current plans to pull it in. We do plan to cherry-pick other improvements.

**Comment by truanguyenvan** [comment]
Thank you for replying to me and I can't see your plan or roadmap at the moment, how can I find it?

**Comment by davidzhao** [comment]
we'll publish it soon!

**Comment by gabrieljbaker** [comment]
How soon do you mean @davidzhao ? :)  Is that linked anywhere I'm not seeing?
