### ISSUE TITLE
Recording each video and audio track seperately

### ISSUE THREAD

**Issue by marlocarlo** [livekit/livekit-server#98]
Hi,
Thanks for developing livekit. It looks fantastic.
I'm building an app to perform actions based on user behaviours.
Is it possible to get the tracks of each individual participant on the server?

Thanks.

**Comment by davidzhao** [comment]
you definitely can. both [GetParticipant](https://docs.livekit.io/guides/server-api#getparticipant) and [ListParticipants](https://docs.livekit.io/guides/server-api#listparticipants) would return a list of tracks.

**Comment by davidzhao** [comment]
I see you might be referring to recording. that's not supported by our recorder at the moment.
There are two ways to accomplish what you are looking to do:
* Build a custom web page to use with the recorder, and spinning up a recorder for each participant you'd want to record.
* Use our [Go SDK](https://github.com/livekit/server-sdk-go) and react to each track subscribed. Save it to any file that you wish.

**Comment by theleapofcode** [comment]
> I see you might be referring to recording. that's not supported by our recorder at the moment. There are two ways to accomplish what you are looking to do:
> 
> * Build a custom web page to use with the recorder, and spinning up a recorder for each participant you'd want to record.
> * Use our [Go SDK](https://github.com/livekit/server-sdk-go) and react to each track subscribed. Save it to any file that you wish.

@davidzhao Can you please provide an example on how to do that. Following https://github.com/livekit/livekit-server/issues/59#issuecomment-955639311 does not work properly.

**Comment by davidzhao** [comment]
We now have [Egress service](https://github.com/livekit/egress) that does exactly this.
